[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags =
    -DUSER_SETUP_LOADED=1
    -I src/display
    -I src/core
    -I src/pet
    -I src/interaction
    -I src/persistence
    -I src/web
    -I src/app
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.0
    tzapu/WiFiManager @ ^2.0.16
